---------------------------------------테이블 드랍
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP INDEX IF EXISTS idx_employee_emp_id CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS emp_tag CASCADE;

---------------------------------------테이블 생성
CREATE TABLE IF NOT EXISTS department
(
    dno bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT department_pkey PRIMARY KEY (dno),
    CONSTRAINT uk_department_name UNIQUE (name),
    CONSTRAINT department_name_check CHECK (name::text = ANY (ARRAY['PROGRAMMING'::character varying, 'DESIGN'::character varying, 'MARKETING'::character varying, 'SALES'::character varying, 'HR'::character varying, 'FINANCE'::character varying, 'OPERATIONS'::character varying, 'CUSTOMER_SERVICE'::character varying, 'IT_SUPPORT'::character varying, 'LEGAL'::character varying, 'RESEARCH'::character varying]::text[]))
)

TABLESPACE pg_default;
ALTER TABLE IF EXISTS department OWNER to postgres;

CREATE TABLE IF NOT EXISTS emp_tag
(
    tno bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    tag character varying(64) COLLATE pg_catalog."default" NOT NULL,
    eno bigint NOT NULL,
    CONSTRAINT emp_tag_pkey PRIMARY KEY (tno),
    CONSTRAINT uk_employee_tag UNIQUE (tag),
    CONSTRAINT emp_tag_tag_check CHECK (tag::text = ANY (ARRAY['HEALTH__GENERAL'::character varying, 'HEALTH__SLEEP'::character varying, 'HEALTH__CARDIOVASCULAR'::character varying, 'HEALTH__DIGESTIVE'::character varying, 'HEALTH__BONE'::character varying, 'HEALTH__SKIN'::character varying, 'HEALTH__EYE'::character varying, 'HEALTH__EAR'::character varying, 'HEALTH__FAMILY'::character varying, 'HEALTH__CHRONIC_DISEASE'::character varying, 'HEALTH__ALLERGY'::character varying, 'HEALTH__PAIN'::character varying, 'HEALTH__PREVENTION'::character varying, 'EXERCISE__GENERAL'::character varying, 'EXERCISE__CARDIO'::character varying, 'EXERCISE__STRENGTH'::character varying, 'EXERCISE__FLEXIBILITY'::character varying, 'EXERCISE__BALANCE'::character varying, 'EXERCISE__YOGA'::character varying, 'EXERCISE__PILATES'::character varying, 'EXERCISE__AEROBIC_DANCE'::character varying, 'EXERCISE__CYCLING'::character varying, 'EXERCISE__RUNNING'::character varying, 'EXERCISE__SWIMMING'::character varying, 'EXERCISE__WALKING'::character varying, 'EXERCISE__STRETCHING'::character varying, 'EXERCISE__HIIT'::character varying, 'EXERCISE__BODYWEIGHT'::character varying, 'EXERCISE__WEIGHTLIFTING'::character varying, 'EXERCISE__PERSONAL_TRAINING'::character varying, 'NUTRIENT__GENERAL'::character varying, 'NUTRIENT__VITAMIN_A'::character varying, 'NUTRIENT__VITAMIN_B'::character varying, 'NUTRIENT__VITAMIN_C'::character varying, 'NUTRIENT__VITAMIN_D'::character varying, 'NUTRIENT__VITAMIN_E'::character varying, 'NUTRIENT__VITAMIN_K'::character varying, 'NUTRIENT__MINERALS'::character varying, 'NUTRIENT__CALCIUM'::character varying, 'NUTRIENT__IRON'::character varying, 'NUTRIENT__MAGNESIUM'::character varying, 'NUTRIENT__ZINC'::character varying, 'NUTRIENT__OMEGA3'::character varying, 'NUTRIENT__PROTEIN'::character varying, 'NUTRIENT__FIBER'::character varying, 'NUTRIENT__ANTIOXIDANTS'::character varying, 'NUTRIENT__HERBAL_SUPPLEMENTS'::character varying, 'NUTRIENT__SUPPLEMENTS'::character varying, 'CARBS__COMPLEX'::character varying, 'CARBS__SIMPLE'::character varying, 'CARBS__RESISTANT_STARCH'::character varying, 'CARBS__LOW_GI'::character varying, 'CARBS__HIGH_GI'::character varying, 'CARBS__WHOLE_GRAINS'::character varying, 'CARBS__REFINED_GRAINS'::character varying, 'CARBS__ADDED_SUGARS'::character varying, 'DIET__BALANCED'::character varying, 'DIET__HIGH_CARB'::character varying, 'DIET__LOW_CARB'::character varying, 'DIET__HIGH_PROTEIN'::character varying, 'DIET__KETO'::character varying, 'DIET__MEDITERRANEAN'::character varying, 'DIET__PALEO'::character varying, 'DIET__LOW_FAT'::character varying, 'DIET__VEGAN'::character varying, 'DIET__GLUTEN_FREE'::character varying, 'DIET__LACTOSE_FREE'::character varying, 'DIET__CARB_CYCLING'::character varying, 'MENTAL__MEDITATION'::character varying, 'MENTAL__STRESS_MANAGEMENT'::character varying, 'MENTAL__HEALTH'::character varying, 'STRESS__NONE'::character varying, 'STRESS__VERY_LOW'::character varying, 'STRESS__LOW'::character varying, 'STRESS__MODERATE'::character varying, 'STRESS__HIGH'::character varying, 'STRESS__VERY_HIGH'::character varying, 'MEDICAL__PHYSICAL_THERAPY'::character varying, 'MEDICAL__REHABILITATION'::character varying, 'MEDICAL__GENERAL'::character varying, 'CONDITION__DIABETES'::character varying, 'CONDITION__HYPERTENSION'::character varying, 'CONDITION__OBESITY'::character varying, 'CONDITION__HYPERLIPIDEMIA'::character varying, 'CONDITION__NAFLD'::character varying, 'CONDITION__THYROID'::character varying, 'CONDITION__PCOS'::character varying, 'LIFESTYLE__NON_SMOKER'::character varying, 'LIFESTYLE__SMOKER'::character varying, 'LIFESTYLE__EX_SMOKER'::character varying, 'OTHER__ANTI_AGING'::character varying, 'OTHER__IMMUNITY'::character varying, 'OTHER__WEIGHT_LOSS'::character varying]::text[]))
)

TABLESPACE pg_default;
ALTER TABLE IF EXISTS emp_tag OWNER to postgres;

CREATE TABLE IF NOT EXISTS employee
(
    eno bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone NOT NULL DEFAULT LOCALTIMESTAMP,
    deleted_at timestamp without time zone,
    emp_address character varying(256) COLLATE pg_catalog."default" NOT NULL,
    emp_address_detail character varying(256) COLLATE pg_catalog."default" NOT NULL,
    emp_email character varying(128) COLLATE pg_catalog."default" NOT NULL,
    emp_id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    emp_name character varying(64) COLLATE pg_catalog."default" NOT NULL,
    emp_phone character varying(32) COLLATE pg_catalog."default" NOT NULL,
    emp_position character varying(32) COLLATE pg_catalog."default" NOT NULL,
    emp_profile_name character varying(256) COLLATE pg_catalog."default",
    emp_pwd character varying(256) COLLATE pg_catalog."default" NOT NULL,
    updated_at timestamp without time zone,
    welfare_points bigint NOT NULL DEFAULT 0,
    dno bigint NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY (eno),
    CONSTRAINT uk_employee_emp_id UNIQUE (emp_id),
	CONSTRAINT uk_employee_emp_phone UNIQUE (emp_phone),
	CONSTRAINT uk_employee_emp_email UNIQUE (emp_email),
    CONSTRAINT fk_department_no_to_employee FOREIGN KEY (dno)
        REFERENCES department (dno) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT employee_emp_position_check CHECK (emp_position::text = ANY (ARRAY['Employee'::character varying, 'Associate'::character varying, 'AssistantManager'::character varying, 'Manager'::character varying, 'SeniorManager'::character varying, 'DepartmentHead'::character varying, 'Director'::character varying, 'ChiefExecutiveOfficer'::character varying, 'Chairman'::character varying]::text[]))
)

TABLESPACE pg_default;
ALTER TABLE IF EXISTS employee OWNER to postgres;

CREATE INDEX IF NOT EXISTS idx_employee_emp_id
    ON employee USING btree
    (emp_id COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS role
(
    no bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    role_type character varying(64) COLLATE pg_catalog."default" NOT NULL,
    employee_no bigint NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (no),
    CONSTRAINT fk_employee_no_to_role FOREIGN KEY (employee_no)
        REFERENCES public.employee (eno) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT role_role_type_check CHECK (role_type::text = ANY (ARRAY['USER'::character varying, 'MANAGER'::character varying, 'ADMIN'::character varying]::text[]))
)

TABLESPACE pg_default;
ALTER TABLE IF EXISTS role OWNER to postgres;


---------------------------------------테이블에 값 insert
BEGIN;
-- 부서
INSERT INTO department(name)VALUES
('PROGRAMMING'),
('DESIGN'),
('MARKETING'),
('SALES'),
('HR'),
('FINANCE'),
('OPERATIONS'),
('CUSTOMER_SERVICE'),
('IT_SUPPORT'),
('LEGAL'),
('RESEARCH')
;

-- 1번 사용자에게 태그 부여
INSERT INTO emp_tag(tag, eno) VALUES
('HEALTH__GENERAL', 1),
('NUTRIENT__VITAMIN_A', 1),
('NUTRIENT__VITAMIN_B', 1),
('NUTRIENT__VITAMIN_C', 1),
('NUTRIENT__VITAMIN_D', 1),
('NUTRIENT__MAGNESIUM', 1),
('NUTRIENT__PROTEIN', 1)
;

-- 관리자 계정 (아이디: admin, 비밀번호: 1234)
-- 사용자 계정 (아이디: user01, 비밀번호: 1234)
-- 사용자 계정 (아이디: user02, 비밀번호: 1234)
INSERT INTO employee(eno, created_at, deleted_at, emp_id, emp_name, emp_position, emp_pwd, updated_at, dno, emp_profile_name, welfare_points, emp_email, emp_phone, emp_address, emp_address_detail) VALUES
(0, LOCALTIMESTAMP, null, 'admin', '관리자', 'Manager', '$2a$10$Lw1gCUrk76ALu40KzzAQ3.Ewn0jeQ1nU6Hk7JpM0rGVbPtTJlVad6', null, 1, null, 0, 'team119@gmail.com', '010-0000-0000', '서울특별시, 관악구', '관악로 0'),
(1, LOCALTIMESTAMP, null, 'user01', '곽사원', 'Employee', '$2a$10$Lw1gCUrk76ALu40KzzAQ3.Ewn0jeQ1nU6Hk7JpM0rGVbPtTJlVad6', null, 1, null, 200000, 'empNo1@gmail.com', '010-1111-1111', '서울특별시, 관악구', '관악로 1'),
(2, LOCALTIMESTAMP, null, 'user02', '김사원', 'Employee', '$2a$10$Lw1gCUrk76ALu40KzzAQ3.Ewn0jeQ1nU6Hk7JpM0rGVbPtTJlVad6', null, 1, null, 194920, 'empNo2@gmail.com', '010-2222-2222', '서울특별시, 관악구', '관악로 2')
;

-- 관리자, 사용자 권한 부여 - (role_type [USER][MANGER][ADMIN])
INSERT INTO role(employee_no, role_type) VALUES
(0, 'ADMIN'),
(1, 'USER'),
(2, 'USER')
;

ALTER TABLE employee ALTER COLUMN eno RESTART WITH 3;

COMMIT;