DROP TABLE IF EXISTS faq_category CASCADE;
DROP TABLE IF EXISTS faq CASCADE;

CREATE TABLE IF NOT EXISTS faq_category
(
    faq_category_no bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    faq_category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT faq_category_pkey PRIMARY KEY (faq_category_no),
    CONSTRAINT uk_faq_category_name UNIQUE (faq_category_name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS faq_category OWNER to postgres;

CREATE TABLE IF NOT EXISTS faq
(
    faq_no bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    del_yn character(1) COLLATE pg_catalog."default" NOT NULL,
    faq_answer text COLLATE pg_catalog."default" NOT NULL,
    faq_ask character varying(256) COLLATE pg_catalog."default" NOT NULL,
    faq_category_no bigint,
    CONSTRAINT faq_pkey PRIMARY KEY (faq_no),
    CONSTRAINT fa_faq_categoty_no_to_faq FOREIGN KEY (faq_category_no)
        REFERENCES faq_category (faq_category_no) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT faq_del_yn_check CHECK (del_yn = ANY (ARRAY['N'::bpchar, 'Y'::bpchar]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS faq OWNER to postgres;


INSERT INTO faq_category(faq_category_name) VALUES
('운동'),
('식단'),
('영양제'),
('기타'),
('복지포인트'),
('지킴이몰')
;

INSERT INTO faq(del_yn, faq_answer, faq_ask, faq_category_no) VALUES
('N', '운동은 일주일에 3~5회, 30분 이상 유산소 운동과 근력 운동을 병행하는 것이 좋습니다. 개인의 체력과 목표에 따라 운동 강도와 빈도를 조절하세요.', '운동은 얼마나 자주 해야 하나요?', 1),
('N', '근력 운동은 주 2~3회, 유산소 운동은 주 3~5회가 권장됩니다. 각 세션은 최소 30분 이상 지속하는 것이 좋습니다.', '근력 운동과 유산소 운동의 권장 빈도는 어떻게 되나요?', 1),
('N', '운동 전에는 가벼운 스트레칭과 워밍업을 통해 몸을 준비시키고, 운동 후에는 쿨다운과 스트레칭으로 근육을 이완시키는 것이 중요합니다.', '운동 전후에 어떤 준비와 마무리를 해야 하나요?', 1),
('N', '식단은 균형 잡힌 영양소 섭취가 중요합니다. 단백질, 탄수화물, 지방, 비타민, 미네랄을 골고루 포함한 식사를 하세요.', '균형 잡힌 식단이란 무엇인가요?', 2),
('N', '체중 감량을 원한다면 하루 섭취 칼로리를 줄이고, 단백질 섭취를 늘리며, 가공식품과 설탕 섭취를 줄이는 것이 도움이 됩니다.', '체중 감량을 위한 식단 조절 방법은?', 2),
('N', '식사 시간은 규칙적으로 유지하는 것이 좋으며, 하루 세 끼를 균형 있게 섭취하고 간식을 적절히 조절하세요.', '식사 시간과 횟수는 어떻게 해야 하나요?', 2),
('N', '비타민 D는 햇빛을 통해 자연스럽게 합성되며, 뼈 건강과 면역 기능에 중요합니다. 하루 600-800 IU의 비타민 D 섭취가 권장됩니다.', '비타민 D의 역할과 권장 섭취량은?', 3),
('N', '오메가-3 지방산은 심혈관 건강에 도움을 주며, 하루 250-500 mg의 EPA와 DHA 섭취가 권장됩니다.', '오메가-3 지방산의 효과와 권장 섭취량은?', 3),
('N', '프로바이오틱스는 장 건강에 도움을 주며, 요구르트, 김치, 된장 등 발효 식품을 통해 섭취할 수 있습니다.', '프로바이오틱스의 역할과 섭취 방법은?', 3),
('N', '충분한 수면은 신체 회복과 면역력 강화에 중요합니다. 성인은 하루 7-9시간의 수면을 권장합니다.', '충분한 수면이 왜 중요한가요?', 4),
('N', '스트레스 관리는 명상, 요가, 심호흡 운동 등을 통해 할 수 있으며, 규칙적인 운동과 취미 활동도 도움이 됩니다.', '스트레스 관리를 위한 방법은?', 4),
('N', '물은 신체 기능 유지에 필수적이며, 하루 8잔(약 2리터)의 물 섭취가 권장됩니다. 개인의 활동량과 환경에 따라 조절하세요.', '하루 물 섭취량은 얼마나 되나요?', 4),
('N', '챌린지에 참여하여 랭킹이 산정되면 순위별로 포인트가 지급됩니다. 또는 매월 1일 정기 지급됩니다.', '복지 포인트는 어떻게 얻을 수 있나요?', 5),
('N', '지킴이몰 메뉴에 접속하여 상품을 장바구니에 담아 결제 버튼을 누르세요.', '지킴이몰은 어떻게 이용하나요?', 6)
;