-- =========================================================
-- Drop (FK 순서 고려)
-- =========================================================
DROP TABLE IF EXISTS RESEARCH_RESULT CASCADE;
DROP TABLE IF EXISTS QUESTION_OPTION CASCADE;
DROP TABLE IF EXISTS RESEARCH_QUESTIONS CASCADE;
DROP TABLE IF EXISTS RESEARCH CASCADE;

-- =========================================================
-- RESEARCH  (ResearchEntity)
--  - @Table(name="RESEARCH")
--  - PK: no (Long, IDENTITY)
--  - FK 컬럼만 생성: eno (@JoinColumn(name="eno")), 제약은 보류
--  - 필드: title(String), description(String), cycle(LocalDate), required(String),
--          category(EnumType.STRING), createdAt/updatedAt/deletedAt(LocalDateTime)
-- =========================================================
CREATE TABLE IF NOT EXISTS RESEARCH
(
    no          BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
        (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),

    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    topic       VARCHAR(255),
    cycle       DATE,
    required    VARCHAR(255),
    category    VARCHAR(255),             -- EnumType.STRING

    created_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at   TIMESTAMP(6) WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT RESEARCH_pkey PRIMARY KEY (no)
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS RESEARCH OWNER TO postgres;

-- =========================================================
-- RESEARCH_QUESTIONS  (QuestionEntity)
--  - @Table(name="RESEARCH_QUESTIONS")
--  - PK: no (Long, IDENTITY)
--  - FK: rno -> RESEARCH.no
--  - 필드: question(String, not null), required(String, not null [오타 그대로]),
--          createdAt/updatedAt/deletedAt(LocalDateTime)
-- =========================================================
CREATE TABLE IF NOT EXISTS RESEARCH_QUESTIONS
(
    no         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
        (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),

    rno        BIGINT NOT NULL,
    question   VARCHAR(255) NOT NULL,
    required   VARCHAR(255) NOT NULL,     -- 엔티티 철자 그대로

    created_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT RESEARCH_QUESTIONS_pkey PRIMARY KEY (no),
    CONSTRAINT RESEARCH_QUESTIONS_fk_research
        FOREIGN KEY (rno) REFERENCES RESEARCH (no) ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS RESEARCH_QUESTIONS OWNER TO postgres;

CREATE INDEX IF NOT EXISTS idx_RESEARCH_QUESTIONS_rno
    ON RESEARCH_QUESTIONS (rno);

-- =========================================================
-- QUESTION_OPTION  (QuestionOptionEntity)
--  - @Table(name="QUESTION_OPTION")
--  - PK: ono (Long, IDENTITY)
--  - FK: qno -> RESEARCH_QUESTIONS.no
--  - 필드: option(String, not null), value(int, not null)
-- =========================================================
CREATE TABLE IF NOT EXISTS QUESTION_OPTION
(
    ono        BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
        (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),

    qno        BIGINT NOT NULL,
    option     VARCHAR(255) NOT NULL,
    value      INTEGER NOT NULL,

    CONSTRAINT QUESTION_OPTION_pkey PRIMARY KEY (ono),
    CONSTRAINT QUESTION_OPTION_fk_question
        FOREIGN KEY (qno) REFERENCES RESEARCH_QUESTIONS (no) ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS QUESTION_OPTION OWNER TO postgres;

CREATE INDEX IF NOT EXISTS idx_QUESTION_OPTION_qno
    ON QUESTION_OPTION (qno);

-- =========================================================
-- RESEARCH_RESULT  (ResultEntity)
--  - @Table(name="RESEARCH_RESULT")
--  - PK: no (Long, IDENTITY)
--  - FK: rno -> RESEARCH.no
--  - 필드: attemptNo(int), score(int), summary(String), submitDate(LocalDate)
-- =========================================================
CREATE TABLE IF NOT EXISTS RESEARCH_RESULT
(
    no         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
        (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),
    eno         BIGINT NOT NULL,                  -- @JoinColumn(name="eno"), FK 제약은 미적용
    rno        BIGINT NOT NULL,
    attempt_no  INTEGER,
    score      INTEGER,
    summary    VARCHAR(255),
    submit_date DATE,

    CONSTRAINT RESEARCH_RESULT_pkey PRIMARY KEY (no),
    CONSTRAINT RESEARCH_RESULT_fk_research
        FOREIGN KEY (rno) REFERENCES RESEARCH (no) ON DELETE CASCADE
)
TABLESPACE pg_default;
ALTER TABLE IF EXISTS RESEARCH_RESULT OWNER TO postgres;

CREATE INDEX IF NOT EXISTS idx_RESEARCH_RESULT_rno
    ON RESEARCH_RESULT (rno);

-- =========================================================
-- LIFESTYLE #1 : 수면 습관 자가진단 (rno = 1)
-- 밴드: 0–54 취약 / 55–69 보통 / 70–84 양호 / 85–100 매우 양호
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('수면 습관 자가진단', '수면 시간과 수면 위생을 점검하는 설문입니다.', 'SLEEP',DATE '2025-10-04', 'Y', 'LIFESTYLE', NOW());

-- qno 1
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '평균 수면 시간은 얼마나 됩니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(1,'4시간 이하',1),
(1,'5~6시간',2),
(1,'6~7시간',3),
(1,'7~8시간',5),
(1,'8시간 초과',4);

-- qno 2
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '잠들기까지 걸리는 시간은 어느 정도입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(2,'60분 이상',1),
(2,'45~60분',2),
(2,'30~45분',3),
(2,'20~30분',4),
(2,'20분 이내',5);

-- qno 3
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '야간에 깬 횟수는 얼마입니까? (지난 1주 평균)', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(3,'4회 이상',1),
(3,'3회',2),
(3,'2회',3),
(3,'1회',4),
(3,'없음',5);

-- qno 4
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '주중과 주말의 수면 시간 차이는 어느 정도입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(4,'4시간 이상',1),
(4,'3시간',2),
(4,'2시간',3),
(4,'1시간',4),
(4,'1시간 이하',5);

-- qno 5
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '오후 2시 이후 카페인 섭취 빈도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(5,'거의 매일',1),
(5,'주 4~5회',2),
(5,'주 2~3회',3),
(5,'주 1회',4),
(5,'없음',5);

-- qno 6
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '코골이/무호흡을 주변에서 지적받은 적이 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(6,'매우 자주',1),
(6,'자주',2),
(6,'가끔',3),
(6,'드묾',4),
(6,'없음',5);

-- qno 7
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '기상 후 개운함은 어느 정도입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(7,'전혀 개운하지 않다',1),
(7,'별로',2),
(7,'보통',3),
(7,'대체로 개운하다',4),
(7,'매우 개운하다',5);

-- qno 8
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (1, '취침/기상 시간이 규칙적입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(8,'전혀 규칙적이지 않다',1),
(8,'드물게 규칙적이다',2),
(8,'보통',3),
(8,'대체로 규칙적이다',4),
(8,'매우 규칙적이다',5);

-- 결과(시도 1~5): 점수 → 밴드 요약
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1000,1,1,56,'LOW',DATE '2025-10-02'),
(1000,1,2,64,'LOW',DATE '2025-10-04'),
(1000,1,3,68,'LOW',DATE '2025-10-05'),
(1000,1,4,80,'MODERATE',DATE '2025-10-08'),
(1000,1,5,93,'HIGH',DATE '2025-10-11');



-- =========================================================
-- LIFESTYLE #2 : 일과-생활 균형 체크 (rno = 2)
-- 밴드: 0–54 취약 / 55–69 보통 / 70–84 양호 / 85–100 매우 양호
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('일과-생활 균형 체크', '업무와 생활의 균형을 확인하는 설문입니다.', 'LIFEBALANCE', DATE '2025-10-07', 'N', 'LIFESTYLE', NOW());

-- qno 9
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '하루 평균 여가/휴식 시간은 어느 정도입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(9,'거의 없음(30분 미만)',1),
(9,'0.5~1시간',2),
(9,'1~2시간',3),
(9,'2~3시간',4),
(9,'3시간 이상',5);

-- qno 10
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '업무 후 완전한 휴식을 취하는 날은 주 몇 회입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(10,'없음',1),
(10,'주 1회',2),
(10,'주 2회',3),
(10,'주 3~4회',4),
(10,'주 5회 이상',5);

-- qno 11
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '업무 이메일/메신저를 퇴근 후 확인합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(11,'항상',1),
(11,'자주',2),
(11,'가끔',3),
(11,'드물게',4),
(11,'전혀 안 함',5);

-- qno 12
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '개인 취미 활동 시간을 확보하고 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(12,'전혀 아니다',1),
(12,'아니다',2),
(12,'보통이다',3),
(12,'그렇다',4),
(12,'매우 그렇다',5);

-- qno 13
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '주중 수면 부족을 주말에 보충합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(13,'항상',1),
(13,'자주',2),
(13,'가끔',3),
(13,'드물게',4),
(13,'전혀 없음',5);

-- qno 14
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '업무 스트레스로 생활에 지장이 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(14,'매우 그렇다',1),
(14,'그렇다',2),
(14,'보통이다',3),
(14,'아니다',4),
(14,'전혀 아니다',5);

-- qno 15
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '하루 평균 스마트폰 사용 시간은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(15,'6시간 이상',1),
(15,'4~6시간',2),
(15,'3~4시간',3),
(15,'2~3시간',4),
(15,'2시간 이하',5);

-- qno 16
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (2, '하루 중 식사 시간을 규칙적으로 지키십니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(16,'전혀 규칙적이지 않다',1),
(16,'드물게 규칙적이다',2),
(16,'보통',3),
(16,'대체로 규칙적이다',4),
(16,'매우 규칙적이다',5);

-- 결과(시도 1~5): 워라밸 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1001,2,1,47,'LOW',DATE '2025-10-02'),
(1001,2,2,66,'MODERATE',DATE '2025-10-03'),
(1001,2,3,71,'MODERATE',DATE '2025-10-05'),
(1001,2,4,79,'MODERATE',DATE '2025-10-08'),
(1001,2,5,85,'HIGH',DATE '2025-10-11');



-- =========================================================
-- LIFESTYLE #3 : 디지털 사용 습관 점검 (rno = 3)
-- 밴드: 0–54 과다 / 55–69 주의 / 70–84 적정 / 85–100 매우 모범적
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('디지털 사용 습관 점검', '디지털 기기 사용 습관을 점검하는 설문입니다.', 'DIGITALHABIT', DATE '2025-10-10', 'Y', 'LIFESTYLE', NOW());

-- qno 17
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, '하루 스마트폰 사용 시간은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(17,'6시간 이상',1),
(17,'4~6시간',2),
(17,'3~4시간',3),
(17,'2~3시간',4),
(17,'2시간 이하',5);

-- qno 18
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, '취침 1시간 전 화면(스마트폰/TV)을 사용합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(18,'항상',1),
(18,'자주',2),
(18,'가끔',3),
(18,'드물게',4),
(18,'전혀 안 함',5);

-- qno 19
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, 'SNS 알림 때문에 집중이 방해받습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(19,'매우 자주',1),
(19,'자주',2),
(19,'가끔',3),
(19,'드묾',4),
(19,'없음',5);

-- qno 20
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, '업무 시간 중 개인적 앱을 사용합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(20,'매우 자주',1),
(20,'자주',2),
(20,'가끔',3),
(20,'드묾',4),
(20,'없음',5);

-- qno 21
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, '앱 알림을 목적에 맞게 관리하고 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(21,'전혀 아니다',1),
(21,'아니다',2),
(21,'보통이다',3),
(21,'그렇다',4),
(21,'매우 그렇다',5);

-- qno 22
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, '디지털 휴식(눈/목 스트레칭)을 실천합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(22,'전혀 아니다',1),
(22,'아니다',2),
(22,'보통이다',3),
(22,'그렇다',4),
(22,'매우 그렇다',5);

-- qno 23
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, '불필요한 앱/계정을 정리합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(23,'전혀 아니다',1),
(23,'아니다',2),
(23,'보통이다',3),
(23,'그렇다',4),
(23,'매우 그렇다',5);

-- qno 24
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (3, '집중 작업 시 방해 요소를 차단합니까? (방해금지 모드 등)', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(24,'전혀 아니다',1),
(24,'아니다',2),
(24,'보통이다',3),
(24,'그렇다',4),
(24,'매우 그렇다',5);

-- 결과(시도 1~15): 디지털 사용 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1003,3,1,45,'LOW',DATE '2025-10-02'),
(1003,3,2,62,'MODERATE',DATE '2025-10-04'),
(1003,3,3,60,'MODERATE',DATE '2025-10-05'),
(1003,3,4,82,'HIGH',DATE '2025-10-08'),
(1003,3,5,81,'HIGH',DATE '2025-10-11');



-- =========================================================
-- LIFESTYLE #4 : 식사·영양 습관 점검 (rno = 4)
-- 밴드: 0–54 불균형 / 55–69 개선 필요 / 70–84 양호 / 85–100 우수
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('식사·영양 습관 점검', '식사 규칙성과 영양 균형을 확인하는 설문입니다.', 'NUTRITION', DATE '2025-10-13', 'N', 'LIFESTYLE', NOW());

-- qno 25
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '하루 세 끼 식사를 규칙적으로 합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(25,'전혀 아니다',1),
(25,'아니다',2),
(25,'보통이다',3),
(25,'그렇다',4),
(25,'매우 그렇다',5);

-- qno 26
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '가공식품/패스트푸드 섭취 빈도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(26,'거의 매일',1),
(26,'주 4~5회',2),
(26,'주 2~3회',3),
(26,'주 1회',4),
(26,'거의 없음',5);

-- qno 27
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '과일/채소 섭취 빈도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(27,'거의 없음',1),
(27,'주 1회',2),
(27,'주 2~3회',3),
(27,'주 4~5회',4),
(27,'거의 매일',5);

-- qno 28
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '단 음료(탄산/주스) 섭취 빈도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(28,'거의 매일',1),
(28,'주 4~5회',2),
(28,'주 2~3회',3),
(28,'주 1회',4),
(28,'거의 없음',5);

-- qno 29
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '단백질(육류/계란/두부) 섭취는 충분합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(29,'전혀 아니다',1),
(29,'아니다',2),
(29,'보통이다',3),
(29,'그렇다',4),
(29,'매우 그렇다',5);

-- qno 30
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '과식/야식 빈도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(30,'거의 매일',1),
(30,'주 4~5회',2),
(30,'주 2~3회',3),
(30,'주 1회',4),
(30,'거의 없음',5);

-- qno 31
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '수분 섭취(물)량은 적절합니까? (하루 1.5L 이상)', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(31,'전혀 아니다',1),
(31,'아니다',2),
(31,'보통이다',3),
(31,'그렇다',4),
(31,'매우 그렇다',5);

-- qno 32
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (4, '음주 빈도는 어느 정도입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(32,'거의 매일',1),
(32,'주 4~5회',2),
(32,'주 2~3회',3),
(32,'주 1회',4),
(32,'거의 없음',5);

-- 결과(시도 1~5): 영양 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1004,4,1,53,'LOW',DATE '2025-10-02'),
(1004,4,2,57,'LOW',DATE '2025-10-03'),
(1004,4,3,68,'MODERATE',DATE '2025-10-06'),
(1004,4,4,74,'MODERATE',DATE '2025-10-08'),
(1004,4,5,90,'HIGH',DATE '2025-10-11');



-- =========================================================
-- LIFESTYLE #5 : 취미·여가 만족도 평가 (rno = 5)
-- 밴드: 0–54 부족 / 55–69 보통 / 70–84 양호 / 85–100 만족 우수
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('취미·여가 만족도 평가', '취미/여가 활동의 빈도와 만족도를 확인하는 설문입니다.', 'LEISURE', DATE '2025-10-16', 'Y', 'LIFESTYLE', NOW());

-- qno 33
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '주당 취미 활동 일수는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(33,'없음',1),
(33,'1일',2),
(33,'2일',3),
(33,'3~4일',4),
(33,'5일 이상',5);

-- qno 34
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '취미 활동 시간이 충분합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(34,'전혀 아니다',1),
(34,'아니다',2),
(34,'보통이다',3),
(34,'그렇다',4),
(34,'매우 그렇다',5);

-- qno 35
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '취미 활동이 스트레스 완화에 도움이 됩니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(35,'전혀 아니다',1),
(35,'아니다',2),
(35,'보통이다',3),
(35,'그렇다',4),
(35,'매우 그렇다',5);

-- qno 36
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '새로운 활동을 시도하는 편입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(36,'전혀 아니다',1),
(36,'아니다',2),
(36,'보통이다',3),
(36,'그렇다',4),
(36,'매우 그렇다',5);

-- qno 37
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '혼자/타인과의 활동 균형에 만족합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(37,'전혀 아니다',1),
(37,'아니다',2),
(37,'보통이다',3),
(37,'그렇다',4),
(37,'매우 그렇다',5);

-- qno 38
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '여가 비용이 부담됩니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(38,'매우 그렇다',1),
(38,'그렇다',2),
(38,'보통이다',3),
(38,'아니다',4),
(38,'전혀 아니다',5);

-- qno 39
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '지역 커뮤니티/동호회 참여 의향이 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(39,'전혀 없다',1),
(39,'낮다',2),
(39,'보통',3),
(39,'높다',4),
(39,'매우 높다',5);

-- qno 40
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (5, '전반적인 여가 만족도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(40,'매우 낮다',1),
(40,'낮다',2),
(40,'보통',3),
(40,'높다',4),
(40,'매우 높다',5);

-- 결과(시도 1~5): 여가 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1005,5,1,55,'LOW',DATE '2025-10-02'),
(1005,5,2,61,'MODERATE',DATE '2025-10-04'),
(1005,5,3,63,'MODERATE',DATE '2025-10-06'),
(1005,5,4,80,'HIGH',DATE '2025-10-08'),
(1005,5,5,95,'HIGH',DATE '2025-10-11');

-- rno = 6
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('스트레스 수준 스크리닝', '스트레스 수준과 대처 능력을 확인하는 설문입니다.', 'STRESS', DATE '2025-10-04', 'Y', 'MENTAL', NOW());

-- qno 41
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '지난 2주, 스트레스를 자주 느꼈습니까?', 'Y', NOW());

INSERT INTO question_option (qno, option, value) VALUES
(41,'매우 그렇다',1),
(41,'그렇다',2),
(41,'보통이다',3),
(41,'아니다',4),
(41,'전혀 아니다',5);

-- qno 42
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '스트레스를 효과적으로 해소합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(42,'전혀 아니다',1),
(42,'아니다',2),
(42,'보통이다',3),
(42,'그렇다',4),
(42,'매우 그렇다',5);

-- qno 43
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '신체 증상(두통/복통/근육통)을 경험했습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(43,'매우 자주',1),
(43,'자주',2),
(43,'가끔',3),
(43,'드묾',4),
(43,'없음',5);

-- qno 44
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '업무·학습 집중에 어려움이 있었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(44,'항상',1),
(44,'자주',2),
(44,'가끔',3),
(44,'드물게',4),
(44,'없음',5);

-- qno 45
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '감정 조절이 잘 되었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(45,'전혀 아니다',1),
(45,'아니다',2),
(45,'보통이다',3),
(45,'그렇다',4),
(45,'매우 그렇다',5);

-- qno 46
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '대인 관계로 인한 스트레스가 컸습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(46,'매우 그렇다',1),
(46,'그렇다',2),
(46,'보통이다',3),
(46,'아니다',4),
(46,'전혀 아니다',5);

-- qno 47
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '하루를 마친 후 심리적 회복감을 느꼈습니까?', 'Y', NOW());

INSERT INTO question_option (qno, option, value) VALUES
(47,'전혀 아니다',1),
(47,'아니다',2),
(47,'보통이다',3),
(47,'그렇다',4),
(47,'매우 그렇다',5);

-- qno 48
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (6, '최근 2주 동안 즐거움/흥미가 감소했습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(48,'매우 그렇다',1),
(48,'그렇다',2),
(48,'보통이다',3),
(48,'아니다',4),
(48,'전혀 아니다',5);

-- 결과(시도 1~5): 스트레스 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1006,6,1,58,'LOW',DATE '2025-10-02'),
(1006,6,2,65,'MODERATE',DATE '2025-10-04'),
(1006,6,3,64,'MODERATE',DATE '2025-10-05'),
(1006,6,4,70,'MODERATE',DATE '2025-10-08'),
(1006,6,5,86,'HIGH',DATE '2025-10-11');



-- =========================================================
-- MENTAL #2 : 기분·흥미 저하 선별 (rno = 7)
-- 밴드: 0–54 위험 높음 / 55–69 중등도 / 70–84 경미 / 85–100 정상 범위
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('기분·흥미 저하 선별', '기분 저하와 무기력 증상을 점검하는 설문입니다.', 'MOOD', DATE '2025-10-07', 'N', 'MENTAL', NOW());

-- qno 49
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '최근 2주, 대부분의 날에 우울감을 느꼈습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(49,'매우 그렇다',1),
(49,'그렇다',2),
(49,'보통이다',3),
(49,'아니다',4),
(49,'전혀 아니다',5);

-- qno 50
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '예전에 즐겁던 일에서 즐거움을 느낍니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(50,'전혀 아니다',1),
(50,'아니다',2),
(50,'보통이다',3),
(50,'그렇다',4),
(50,'매우 그렇다',5);

-- qno 51
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '수면 문제가 있었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(51,'매우 자주',1),
(51,'자주',2),
(51,'가끔',3),
(51,'드묾',4),
(51,'없음',5);

-- qno 52
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '피로감·에너지 저하가 지속되었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(52,'항상',1),
(52,'자주',2),
(52,'가끔',3),
(52,'드물게',4),
(52,'없음',5);

-- qno 53
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '집중하기 어려웠습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(53,'항상',1),
(53,'자주',2),
(53,'가끔',3),
(53,'드물게',4),
(53,'없음',5);

-- qno 54
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '자책감이나 무가치감을 느꼈습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(54,'매우 자주',1),
(54,'자주',2),
(54,'가끔',3),
(54,'드묾',4),
(54,'없음',5);

-- qno 55
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '식욕 변화(감소/증가)가 있었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(55,'매우 크다',1),
(55,'크다',2),
(55,'보통',3),
(55,'작다',4),
(55,'없음',5);

-- qno 56
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (7, '자해 생각이 스쳐간 적이 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(56,'자주 있었다',1),
(56,'가끔 있었다',2),
(56,'한두 번 있었다',3),
(56,'거의 없다',4),
(56,'전혀 없다',5);

-- 결과(시도 1~10): 우울 선별 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1007,7,1,52,'LOW',DATE '2025-10-02'),
(1007,7,2,60,'MODERATE',DATE '2025-10-04'),
(1007,7,3,58,'LOW',DATE '2025-10-06'),
(1007,7,4,76,'MODERATE',DATE '2025-10-08'),
(1007,7,5,84,'HIGH',DATE '2025-10-11');



-- =========================================================
-- MENTAL #3 : 수면과 정서 상태 체크 (rno = 3)
-- 밴드: 0–54 악화 / 55–69 부분적 영향 / 70–84 대체로 안정 / 85–100 매우 안정
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('수면과 정서 상태 체크', '수면과 정서의 상관을 확인하는 설문입니다.', 'SLEEPEMOTION', DATE '2025-10-10', 'Y', 'MENTAL', NOW());

-- qno 57
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '잠들기 어렵거나 자주 깼습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(57,'매우 자주',1),
(57,'자주',2),
(57,'가끔',3),
(57,'드묾',4),
(57,'없음',5);

-- qno 58
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '수면 부족으로 감정 기복이 심했습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(58,'매우 그렇다',1),
(58,'그렇다',2),
(58,'보통이다',3),
(58,'아니다',4),
(58,'전혀 아니다',5);

-- qno 59
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '기상 후 활력은 어느 정도였습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(59,'매우 낮다',1),
(59,'낮다',2),
(59,'보통',3),
(59,'높다',4),
(59,'매우 높다',5);

-- qno 60
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '낮 시간 졸림을 자주 느꼈습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(60,'항상',1),
(60,'자주',2),
(60,'가끔',3),
(60,'드물게',4),
(60,'없음',5);

-- qno 61
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '수면 위생(취침 전 루틴)을 지켰습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(61,'전혀 아니다',1),
(61,'아니다',2),
(61,'보통이다',3),
(61,'그렇다',4),
(61,'매우 그렇다',5);

-- qno 62
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '악몽이나 불쾌한 꿈을 자주 꾸었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(62,'매우 자주',1),
(62,'자주',2),
(62,'가끔',3),
(62,'드묾',4),
(62,'없음',5);

-- qno 63
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '수면이 하루 컨디션에 긍정적 영향을 주었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(63,'전혀 아니다',1),
(63,'아니다',2),
(63,'보통이다',3),
(63,'그렇다',4),
(63,'매우 그렇다',5);

-- qno 64
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (8, '전반적인 수면 만족도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(64,'매우 낮다',1),
(64,'낮다',2),
(64,'보통',3),
(64,'높다',4),
(64,'매우 높다',5);

-- 결과(시도 1~10): 수면-정서 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1008,8,1,59,'LOW',DATE '2025-10-02'),
(1008,8,2,67,'MODERATE',DATE '2025-10-04'),
(1008,8,3,73,'MODERATE',DATE '2025-10-06'),
(1008,8,4,69,'MODERATE',DATE '2025-10-08'),
(1008,8,5,88,'HIGH',DATE '2025-10-11');



-- =========================================================
-- MENTAL #4 : 집중·피로 자가진단 (rno = 4)
-- 밴드: 0–54 심각 / 55–69 주의 / 70–84 관리 가능 / 85–100 우수
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('집중·피로 자가진단', '집중력과 피로 수준을 확인하는 설문입니다.', 'FOCUSFATIGUE', DATE '2025-10-13', 'N', 'MENTAL', NOW());

-- qno 65
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '하루 중 집중 유지 시간이 짧습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(65,'매우 그렇다',1),
(65,'그렇다',2),
(65,'보통이다',3),
(65,'아니다',4),
(65,'전혀 아니다',5);

-- qno 66
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '작업 중 산만함을 자주 경험합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(66,'항상',1),
(66,'자주',2),
(66,'가끔',3),
(66,'드물게',4),
(66,'없음',5);

-- qno 67
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '짧은 휴식으로 회복이 잘 됩니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(67,'전혀 아니다',1),
(67,'아니다',2),
(67,'보통이다',3),
(67,'그렇다',4),
(67,'매우 그렇다',5);

-- qno 68
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '오전 대비 오후 피로가 심합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(68,'매우 그렇다',1),
(68,'그렇다',2),
(68,'보통이다',3),
(68,'아니다',4),
(68,'전혀 아니다',5);

-- qno 69
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '중요 작업 시 몰입감을 느낍니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(69,'전혀 아니다',1),
(69,'아니다',2),
(69,'보통이다',3),
(69,'그렇다',4),
(69,'매우 그렇다',5);

-- qno 70
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '카페인/당분에 과도하게 의존합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(70,'항상',1),
(70,'자주',2),
(70,'가끔',3),
(70,'드물게',4),
(70,'없음',5);

-- qno 71
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '업무 환경(소음/온도)이 적절합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(71,'전혀 아니다',1),
(71,'아니다',2),
(71,'보통이다',3),
(71,'그렇다',4),
(71,'매우 그렇다',5);

-- qno 72
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (9, '전반적인 피로 수준은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(72,'매우 높다',1),
(72,'높다',2),
(72,'보통',3),
(72,'낮다',4),
(72,'매우 낮다',5);

-- 결과(시도 1~5): 피로 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1009,9,1,56,'LOW',DATE '2025-10-02'),
(1009,9,2,63,'MODERATE',DATE '2025-10-04'),
(1009,9,3,72,'MODERATE',DATE '2025-10-06'),
(1009,9,4,78,'MODERATE',DATE '2025-10-08'),
(1009,9,5,83,'HIGH',DATE '2025-10-11');



-- =========================================================
-- MENTAL #5 : 불안·초조 스크리닝 (rno = 5)
-- 밴드: 0–54 고위험 / 55–69 주의 / 70–84 관리 가능 / 85–100 낮음
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('불안·초조 스크리닝', '불안과 긴장 관련 증상을 선별하는 설문입니다.', 'ANXIETY', DATE '2025-10-16', 'Y', 'MENTAL', NOW());

-- qno 73
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '사소한 일에도 과도하게 걱정합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(73,'항상',1),
(73,'자주',2),
(73,'가끔',3),
(73,'드물게',4),
(73,'없음',5);

-- qno 74
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '긴장/초조로 인해 휴식을 취하기 어렵습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(74,'매우 그렇다',1),
(74,'그렇다',2),
(74,'보통이다',3),
(74,'아니다',4),
(74,'전혀 아니다',5);

-- qno 75
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '심장이 두근거리거나 땀이 나는 증상이 있었습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(75,'매우 자주',1),
(75,'자주',2),
(75,'가끔',3),
(75,'드묾',4),
(75,'없음',5);

-- qno 76
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '예상치 못한 상황을 피하려 합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(76,'항상',1),
(76,'자주',2),
(76,'가끔',3),
(76,'드물게',4),
(76,'없음',5);

-- qno 77
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '긴장 완화를 위한 호흡/명상을 활용합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(77,'전혀 아니다',1),
(77,'아니다',2),
(77,'보통이다',3),
(77,'그렇다',4),
(77,'매우 그렇다',5);

-- qno 78
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '주관적 불안 수준은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(78,'매우 높다',1),
(78,'높다',2),
(78,'보통',3),
(78,'낮다',4),
(78,'매우 낮다',5);

-- qno 79
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '수면에 불안이 영향을 줍니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(79,'매우 그렇다',1),
(79,'그렇다',2),
(79,'보통이다',3),
(79,'아니다',4),
(79,'전혀 아니다',5);

-- qno 80
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (10, '불안으로 일상 기능에 지장이 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(80,'항상',1),
(80,'자주',2),
(80,'가끔',3),
(80,'드물게',4),
(80,'없음',5);

-- 결과(시도 1~5): 불안 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1010,10,1,54,'LOW',DATE '2025-10-02'),
(1010,10,2,62,'MODERATE',DATE '2025-10-04'),
(1010,10,3,66,'MODERATE',DATE '2025-10-06'),
(1010,10,4,81,'HIGH',DATE '2025-10-09'),
(1010,10,5,85,'HIGH',DATE '2025-10-11');

INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('유산소 활동 수준 평가', '유산소 운동 실천 정도를 확인하는 설문입니다.', 'AEROBIC', DATE '2025-10-04', 'Y', 'PHYSICAL', NOW());

-- qno 81
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '주당 유산소 운동 일수는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(81,'없음',1),
(81,'1일',2),
(81,'2일',3),
(81,'3~4일',4),
(81,'5일 이상',5);

-- qno 82
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '평균 세션 시간은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(82,'20분 미만',1),
(82,'20~29분',2),
(82,'30~39분',3),
(82,'40~59분',4),
(82,'60분 이상',5);

-- qno 83
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '운동 강도는 어느 정도입니까? (숨가쁨 기준)', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(83,'거의 없음',1),
(83,'약간',2),
(83,'보통',3),
(83,'다소 힘듦',4),
(83,'매우 힘듦',5);

-- qno 84
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '운동 후 피로 회복은 잘 됩니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(84,'전혀 아니다',1),
(84,'아니다',2),
(84,'보통이다',3),
(84,'그렇다',4),
(84,'매우 그렇다',5);

-- qno 85
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '주중 좌식 시간(앉아있는 시간)은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(85,'10시간 이상',1),
(85,'8~10시간',2),
(85,'6~8시간',3),
(85,'4~6시간',4),
(85,'4시간 미만',5);

-- qno 86
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '계단 이용/걷기 등 생활 활동을 실천합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(86,'전혀 아니다',1),
(86,'아니다',2),
(86,'보통이다',3),
(86,'그렇다',4),
(86,'매우 그렇다',5);

-- qno 87
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '운동 목표를 설정하고 추적합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(87,'전혀 아니다',1),
(87,'아니다',2),
(87,'보통이다',3),
(87,'그렇다',4),
(87,'매우 그렇다',5);

-- qno 88
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (11, '전반적인 유산소 체력에 대한 자가평가는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(88,'매우 낮다',1),
(88,'낮다',2),
(88,'보통',3),
(88,'높다',4),
(88,'매우 높다',5);

-- 결과(시도 1~5): 유산소 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1011,11,1,57,'LOW',DATE '2025-10-02'),
(1011,11,2,61,'MODERATE',DATE '2025-10-04'),
(1011,11,3,70,'MODERATE',DATE '2025-10-06'),
(1011,11,4,68,'MODERATE',DATE '2025-10-08'),
(1011,11,5,82,'HIGH',DATE '2025-10-11');



-- =========================================================
-- PHYSICAL #2 : 근력 운동 습관 평가 (rno = 2)
-- 밴드: 0–54 부족 / 55–69 보통 / 70–84 양호 / 85–100 우수
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('근력 운동 습관 평가', '근력 운동 실천 정도를 확인하는 설문입니다.', 'STRENGTH', DATE '2025-10-07', 'N', 'PHYSICAL', NOW());

-- qno 89
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '주당 근력 운동 일수는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(89,'없음',1),
(89,'1일',2),
(89,'2일',3),
(89,'3~4일',4),
(89,'5일 이상',5);

-- qno 90
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '전신 근육군을 균형 있게 훈련합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(90,'전혀 아니다',1),
(90,'아니다',2),
(90,'보통이다',3),
(90,'그렇다',4),
(90,'매우 그렇다',5);

-- qno 91
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '점진적 과부하 원칙을 적용합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(91,'전혀 아니다',1),
(91,'아니다',2),
(91,'보통이다',3),
(91,'그렇다',4),
(91,'매우 그렇다',5);

-- qno 92
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '운동 전후 스트레칭/워밍업을 합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(92,'전혀 아니다',1),
(92,'아니다',2),
(92,'보통이다',3),
(92,'그렇다',4),
(92,'매우 그렇다',5);

-- qno 93
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '부상 예방을 위한 자세·호흡을 지킵니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(93,'전혀 아니다',1),
(93,'아니다',2),
(93,'보통이다',3),
(93,'그렇다',4),
(93,'매우 그렇다',5);

-- qno 94
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '운동 중 통증을 경험합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(94,'항상',1),
(94,'자주',2),
(94,'가끔',3),
(94,'드물게',4),
(94,'없음',5);

-- qno 95
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '회복을 위한 수면/영양을 관리합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(95,'전혀 아니다',1),
(95,'아니다',2),
(95,'보통이다',3),
(95,'그렇다',4),
(95,'매우 그렇다',5);

-- qno 96
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (12, '근력 향상에 대한 자가평가는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(96,'매우 낮다',1),
(96,'낮다',2),
(96,'보통',3),
(96,'높다',4),
(96,'매우 높다',5);

-- 결과(시도 1~10): 근력 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1012,12,1,50,'LOW',DATE '2025-10-02'),
(1012,12,2,58,'LOW',DATE '2025-10-04'),
(1012,12,3,65,'MODERATE',DATE '2025-10-06'),
(1012,12,4,77,'MODERATE',DATE '2025-10-08'),
(1012,12,5,90,'HIGH',DATE '2025-10-11');



-- =========================================================
-- PHYSICAL #3 : 심혈관 건강 지표 체크 (rno = 3)
-- 밴드: 0–54 위험 높음 / 55–69 주의 / 70–84 관리 중(개선 경향) / 85–100 건강 양호
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('심혈관 건강 지표 체크', '심혈관 건강 관련 생활습관을 확인하는 설문입니다.', 'CARDIOVASCULAR', DATE '2025-10-10', 'Y', 'PHYSICAL', NOW());

-- qno 97
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '최근 1년간 건강검진을 받았습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(97,'전혀 아니다',1),
(97,'아니다',2),
(97,'보통이다',3),
(97,'그렇다',4),
(97,'매우 그렇다',5);

-- qno 98
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '혈압 관리(측정/기록)를 하고 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(98,'전혀 아니다',1),
(98,'아니다',2),
(98,'보통이다',3),
(98,'그렇다',4),
(98,'매우 그렇다',5);

-- qno 99
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '짠 음식을 선호합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(99,'항상',1),
(99,'자주',2),
(99,'가끔',3),
(99,'드물게',4),
(99,'아니오',5);

-- qno 100
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '걷기/계단 이용을 생활화하고 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(100,'전혀 아니다',1),
(100,'아니다',2),
(100,'보통이다',3),
(100,'그렇다',4),
(100,'매우 그렇다',5);

-- qno 101
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '흡연을 합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(101,'현재 흡연',1),
(101,'가끔 흡연',2),
(101,'과거 흡연(금연 중)',3),
(101,'비흡연(간접흡연 있음)',4),
(101,'비흡연(간접흡연 거의 없음)',5);

-- qno 102
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '음주 빈도는 어느 정도입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(102,'거의 매일',1),
(102,'주 4~5회',2),
(102,'주 2~3회',3),
(102,'주 1회',4),
(102,'거의 없음',5);

-- qno 103
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '체중/허리둘레 관리를 하고 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(103,'전혀 아니다',1),
(103,'아니다',2),
(103,'보통이다',3),
(103,'그렇다',4),
(103,'매우 그렇다',5);

-- qno 104
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (13, '유산소/근력 복합운동을 주기적으로 합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(104,'전혀 아니다',1),
(104,'아니다',2),
(104,'보통이다',3),
(104,'그렇다',4),
(104,'매우 그렇다',5);

-- 결과(시도 1~5): 심혈관 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1013,13,1,52,'LOW',DATE '2025-10-02'),
(1013,13,2,63,'MODERATE',DATE '2025-10-03'),
(1013,13,3,61,'MODERATE',DATE '2025-10-05'),
(1013,13,4,75,'MODERATE',DATE '2025-10-08'),
(1013,13,5,87,'HIGH',DATE '2025-10-11');



-- =========================================================
-- PHYSICAL #4 : 대사 건강(혈당·지질) 점검 (rno = 4)
-- 밴드: 0–54 위험 / 55–69 주의 / 70–84 관리 가능 / 85–100 양호
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('대사 건강(혈당·지질) 점검', '혈당·지질 관리와 관련 생활습관을 확인하는 설문입니다.', 'METABOLIC', DATE '2025-10-13', 'N', 'PHYSICAL', NOW());

-- qno 105
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '단 음료/디저트 섭취 빈도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(105,'거의 매일',1),
(105,'주 4~5회',2),
(105,'주 2~3회',3),
(105,'주 1회',4),
(105,'거의 없음',5);

-- qno 106
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '정제탄수화물(흰쌀·빵) 위주 식사입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(106,'항상',1),
(106,'자주',2),
(106,'가끔',3),
(106,'드물게',4),
(106,'아니오',5);

-- qno 107
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '통곡물/식이섬유를 충분히 섭취합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(107,'전혀 아니다',1),
(107,'아니다',2),
(107,'보통이다',3),
(107,'그렇다',4),
(107,'매우 그렇다',5);

-- qno 108
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '주당 유산소 운동을 150분 이상 합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(108,'전혀 아니다',1),
(108,'아니다',2),
(108,'보통이다',3),
(108,'그렇다',4),
(108,'매우 그렇다',5);

-- qno 109
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '최근 혈당/지질 수치를 확인했습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(109,'전혀 아니다',1),
(109,'아니다',2),
(109,'보통이다',3),
(109,'그렇다',4),
(109,'매우 그렇다',5);

-- qno 110
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '과식/야식 빈도는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(110,'거의 매일',1),
(110,'주 4~5회',2),
(110,'주 2~3회',3),
(110,'주 1회',4),
(110,'거의 없음',5);

-- qno 111
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '체중 변동이 큰 편입니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(111,'항상',1),
(111,'자주',2),
(111,'가끔',3),
(111,'드물게',4),
(111,'거의 없음',5);

-- qno 112
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (14, '전반적인 식단 관리 수준은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(112,'매우 낮다',1),
(112,'낮다',2),
(112,'보통',3),
(112,'높다',4),
(112,'매우 높다',5);

-- 결과(시도 1~5): 대사 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1014,14,1,56,'LOW',DATE '2025-10-02'),
(1014,14,2,55,'LOW',DATE '2025-10-03'),
(1014,14,3,64,'MODERATE',DATE '2025-10-05'),
(1014,14,4,71,'MODERATE',DATE '2025-10-08'),
(1014,14,5,84,'HIGH',DATE '2025-10-11');



-- =========================================================
-- PHYSICAL #5 : 체성분·심박 상태 체크 (rno = 5)
-- 밴드: 0–54 불안정 / 55–69 부분적 불균형 / 70–84 대체로 안정 / 85–100 매우 안정
-- =========================================================
INSERT INTO research (title, description, topic, cycle, required, category, created_at)
VALUES ('체성분·심박 상태 체크', '체성분과 심박 안정성을 확인하는 설문입니다.', 'HEART', DATE '2025-10-16', 'Y', 'PHYSICAL', NOW());

-- qno 113
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '최근 6개월간 체중 변화가 컸습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(113,'매우 크다',1),
(113,'크다',2),
(113,'보통',3),
(113,'작다',4),
(113,'거의 없다',5);

-- qno 114
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '평균 휴식 시 심박수는?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(114,'90bpm 이상',1),
(114,'80~89bpm',2),
(114,'70~79bpm',3),
(114,'60~69bpm',4),
(114,'60bpm 미만',5);

-- qno 115
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '주당 체성분(인바디 등) 측정을 합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(115,'전혀 안 함',1),
(115,'연 1~2회',2),
(115,'분기 1회',3),
(115,'월 1회',4),
(115,'월 2회 이상',5);

-- qno 116
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '체지방률 관리가 잘 되고 있습니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(116,'전혀 아니다',1),
(116,'아니다',2),
(116,'보통이다',3),
(116,'그렇다',4),
(116,'매우 그렇다',5);

-- qno 117
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '허리둘레/체중을 기록합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(117,'전혀 안 함',1),
(117,'가끔',2),
(117,'보통',3),
(117,'주간 기록',4),
(117,'매일 기록',5);

-- qno 118
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '활동 링/만보기 등으로 활동량을 측정합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(118,'전혀 안 함',1),
(118,'가끔',2),
(118,'보통',3),
(118,'자주',4),
(118,'항상',5);

-- qno 119
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '체형 균형(자세·유연성)에 만족합니까?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(119,'전혀 아니다',1),
(119,'아니다',2),
(119,'보통이다',3),
(119,'그렇다',4),
(119,'매우 그렇다',5);

-- qno 120
INSERT INTO research_questions (rno, question, required, created_at)
VALUES (15, '전반적인 컨디션은?', 'Y', NOW());
INSERT INTO question_option (qno, option, value) VALUES
(120,'매우 나쁨',1),
(120,'나쁨',2),
(120,'보통',3),
(120,'좋음',4),
(120,'매우 좋음',5);

-- 결과(시도 1~5): 체성분/심박 밴드
INSERT INTO research_result (eno, rno, attempt_no, score, summary, submit_date) VALUES
(1015,15,1,57,'LOW',DATE '2025-10-02'),
(1015,15,2,60,'MODERATE',DATE '2025-10-03'),
(1015,15,3,58,'LOW',DATE '2025-10-05'),
(1015,15,4,79,'MODERATE',DATE '2025-10-08'),
(1015,15,5,88,'HIGH',DATE '2025-10-11');